### ISSUE TITLE
typos and picky stuff

### ISSUE THREAD

**Issue by swheelan** [jhudsl/ITCR_Cancer_informatics_for_PIs#1]
in "About this course" near the end there is a typo in "investigators"
In 2.1.2 there is a typo in "collaborating"
2.1.2 point 3 should be "morale"
2.3 it's should be its
2.3.4.1 point #2 "the city police department"
2.3.4.1 point #3 should be Stitch
2.3.4.1 "a data scientist who formerly"
2.3.4.2 you have two #2s
2.3.4.2 under point #3 should be "main projects fail"
2.3.4.2 points 5-8 should be subpoints under #4
2.3.5 under stereotype threat "miss influence"
2.3.5 typo in microaggressions, again in point #3
2.3.5 point #7 should be "microaffirmations"

**Comment by carriewright11** [comment]
Thanks again!
